name = "cotizador-notarial"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
FIREBASE_PROJECT_ID = "cotizacionesnotariales"

[[kv_namespaces]]
binding = "SHEETS_KV"
id = "fccac705acc346b191cb4cf83cf350e2"
